### ISSUE TITLE
请问大佬这是什么原理，可否留下邮箱私聊

### ISSUE THREAD

**Issue by Way2LOose4** [lz00qs/stuGfw#2]

**Comment by lz00qs** [comment]
没啥原理，就只是个代理桥接而已，建议先完成计算机网络的学习再看

**Comment by Way2LOose4** [comment]
谢谢大哥提供思路，已经搭建好了一个x-ui面板了

**Comment by lz00qs** [comment]
> 谢谢大哥提供思路，已经搭建好了一个x-ui面板了

我已经离校去打黑工了，有不懂的，可以请教 @Yuru-ekis
